site_name: BDWatchdog documentation
nav:
    - Introduction: index.md
    #- Use case: use_case.md
    #- Architecture: architecture.md
    #- Deployment: deployment.md
    - Sponsors: sponsors.md
    - Homepage (external): http://bdwatchdog.dec.udc.es/monitoring/index.html
    - Source code (external): code/index.html


#theme: readthedocs
#theme: mkdocs

theme:
    name: material
    #custom_dir: 'custom_theme/'
    favicon: 'img/icon.png'


# Repository
repo_name: 'JonatanEnes/BDWatchdog'
repo_url: 'https://github.com/JonatanEnes/BDWatchdog'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Jonatan Enes'

markdown_extensions:
  - attr_list