site_name: BDWatchdog documentation
nav:
    - Home: index.md
    - Use case: use_case.md
    - Architecture: architecture.md
    - Deployment: deployment.md
    - Source code: code/index.html
    - Sponsors: sponsors.md

#theme: readthedocs
#theme: mkdocs

theme:
    name: material
    #custom_dir: 'custom_theme/'
    favicon: 'img/favicon.ico'


# Repository
repo_name: 'JonatanEnes/BDWatchdog'
repo_url: 'https://github.com/JonatanEnes/BDWatchdog'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Jonatan Enes'

markdown_extensions:
  - attr_list